"""Reusable local scalar-field generation contracts."""

from .hdf5 import (
    ORIENTATION,
    CellState,
    CompletedTile,
    DatasetValidation,
    DuplicateTileConflict,
    FieldDefinition,
    FieldSnapshot,
    IntegrityError,
    PersistenceError,
    ResumeState,
    TileState,
    assert_dataset_compatible,
    create_dataset,
    discover_resume_state,
    inspect_dataset,
    read_authoritative_field,
    validate_dataset,
    write_completed_tile,
)
from .runner import (
    EvaluatorBinding,
    FieldProgress,
    FieldRunSummary,
    ProcessExecutionSpec,
    ProgressCallback,
    accepted_process_execution_spec,
    run_scalar_field,
)
from .validation import ScalarFieldValidation, validate_authoritative_field
from .work_units import (
    CoverageValidation,
    ScalarCellTask,
    TileBounds,
    TileShape,
    TileWorkUnit,
    plan_tiles,
    tasks_for_work_unit,
    validate_tile_plan,
)

__all__ = [
    "ORIENTATION",
    "CellState",
    "CompletedTile",
    "DatasetValidation",
    "DuplicateTileConflict",
    "FieldDefinition",
    "FieldSnapshot",
    "IntegrityError",
    "PersistenceError",
    "ResumeState",
    "TileState",
    "assert_dataset_compatible",
    "create_dataset",
    "discover_resume_state",
    "inspect_dataset",
    "read_authoritative_field",
    "validate_dataset",
    "write_completed_tile",
    "EvaluatorBinding",
    "FieldProgress",
    "FieldRunSummary",
    "ProcessExecutionSpec",
    "ProgressCallback",
    "accepted_process_execution_spec",
    "run_scalar_field",
    "ScalarFieldValidation",
    "validate_authoritative_field",
    "CoverageValidation",
    "ScalarCellTask",
    "TileBounds",
    "TileShape",
    "TileWorkUnit",
    "plan_tiles",
    "tasks_for_work_unit",
    "validate_tile_plan",
]
